name: ptune
description: "Pomodoro timer app integrated with Google Tasks"

publish_to: "none"

# Flutter launcher icons settings
flutter_icons:
  ios: true
  image_path: "assets/icon/icon_ios.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "assets/icon/icon_adaptive_background.png"
  adaptive_icon_foreground: "assets/icon/icon_adaptive_foreground.png"

version: 1.0.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management / model
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^3.1.0
  json_serializable: ^6.1.5

  # UI / Routing / Utilities
  go_router: ^16.2.0
  logger: ^2.0.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  share_plus: ^12.0.1

  # Platform services
  path_provider: ^2.1.1
  wakelock_plus: ^1.1.3
  window_manager: ^0.5.1

  # OAuth / Authentication
  flutter_dotenv: ^6.0.0
  googleapis_auth: ^2.0.0

  # Firebase Auth (Android/iOS)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  flutter_secure_storage: ^9.2.4

  # Network
  http: 1.5.0

  # Launcher icons
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - assets/tasks.json
    - .env
